quizmakers/quizapp/urls.py
from django.urls import path
from . import views

app_name = 'quizapp'

urlpatterns = [
    path('', views.landingPage, name='landing'),
    path('give_quiz/', views.quizPage, name='quiz'),
    path('quiz/<int:pk>/', views.quiz_detail, name='quiz_detail'),
    path('create_quiz/', views.addQuiz, name='create'),
    path('add_question/<int:pk>',views.addQuestion, name='add_question'),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),  
    path('logout/', views.logoutUser, name="logout"),
    #path('create_question/', views.addQuiz, name='create'),
]

quizmakers/quizmakers/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizapp.urls')),
    
]

quizmakers/quizapp/models.py
from os import name, truncate
from django.db import models

# Create your models here.

class Quiz(models.Model):
    name = models.CharField(max_length=200)
    code=models.CharField(max_length=10,default="12345678")

    def __str__(self) -> str:
        return self.name

class Question(models.Model):
    CORRECT_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
    ]
    question = models.CharField(max_length=2000)
    opt1 = models.CharField(max_length=500)
    opt2 = models.CharField(max_length=500)
    opt3 = models.CharField(max_length=500)
    opt4 = models.CharField(max_length=500)
    correct = models.CharField(
        max_length=1,
        choices=CORRECT_CHOICES,
    )

    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE,related_name='questions',blank=True)
    

    def __str__(self):
        return f"Question {self.pk}"



    

quizmakers/quizapp/forms.py
from django import forms

from .models import Quiz,Question
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class PostQuiz(forms.ModelForm):

    class Meta:
        model=Question
        fields =('question','opt1','opt2','opt3','opt4','correct')

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

quizmakers/quizapp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Question,Quiz
from django.utils import timezone
from .forms import PostQuiz,CreateUserForm
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,UpdateView)
cool=False
# main landing Page
def registerPage(request):
    
    if request.user.is_authenticated:
        return redirect('quizapp:landing')
	
    else:    
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('/login/')
                

        context = {'form':form}
        return render(request, 'register.html', context)

def loginPage(request):

    if request.user.is_authenticated:
        
        return redirect('quizapp:landing')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password =request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                cool=True
                login(request, user)
                if request.POST.get('next'):
                    return redirect(request.POST.get('next'))
                return redirect('quizapp:landing')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('quizapp:landing')



def landingPage(request):
    return render(request,'landing.html')



 
# quizPage and Details
@login_required(login_url='quizapp:login')

def quizPage(request):
    if request.method=='POST':
        code=request.POST.get('code')
        quiz =  Quiz.objects.filter(code=str(code))
        if quiz:
            return redirect('/quiz/'+str(quiz[0].pk)+'' )
           
        return render(request,'give_quiz.html',{'quiz':quiz,'value':True})
    else:
        quiz =  Quiz.objects.all
        return render(request,'give_quiz.html',{'quiz':quiz,'value':False})


@login_required(login_url='quizapp:login')

def quiz_detail(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    if request.method == 'POST':
        response = request.POST
        # print(response)
        cor = 0
        for i in response:
            i = i.split(' ')
            if i[0] == 'Question':
                ans = Question.objects.get(pk=int(i[1])).correct
                resp = response['Question '+i[1]]
                # print(resp, ans)
                if resp == ans:
                    cor += 1
        # print("No. of correct answers: ", cor, ".")
        return render(request, 'result.html', {'quiz': quiz, 'correct': cor})
        
    else:
        return render(request, 'quiz_detail.html', {'quiz': quiz})




#creating quiz
@login_required(login_url='quizapp:login')
def addQuiz(request):
    

    if request.method == 'POST':
       
        cod=request.POST.get('code')
        value =  Quiz.objects.filter(code=str(cod))
        if value:
            return render(request, 'create_quiz.html',{'cool':True})
        quiz = Quiz()
       
        quiz.name = request.POST.get('quiz_name')
        quiz.code=request.POST.get('code')
        quiz.save()
        quiz = Quiz.objects.all().last()
        k=quiz.pk
        s='/add_question/'+str(k)+''
        
        return redirect(s)
    else:
        return render(request, 'create_quiz.html',{'cool':False})

@login_required(login_url='quizapp:login')
def addQuestion(request,pk):
    quiz = get_object_or_404(Quiz, pk=pk)
   
    if request.method =='POST':
        form = PostQuiz(request.POST)
        if form.is_valid():
            quest =form.save(commit=False)
            #quest.question= request.POST.get('question')
            quest.quiz=quiz
            
            quest.save()
            
       # quest=Question.objects.all().last()
            return render(request,'update.html',{'PK':pk})
    else:
        form = PostQuiz()
        return render(request,'create_question.html',{'form':form})

quizmakers/templates/base.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	<title>Squeeze</title>
	<meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'css/footer.css' %}"> -->
  <link rel="stylesheet" href="{% static 'css/1.css' %}">



</head>
<style>

</style>
<body >
  <nav>
    <input type="checkbox" id="check">
    <label for="check" class="checkbtn">
      <i class="fa fa-bars"></i>
    </label>
    <label class="logo"><a class="nav-link" href="{% url 'quizapp:landing' %}">Squeeze</a></label>
    <ul>
      <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:quiz' %}">Give quiz</a></li>
      <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:create' %}">Create a quiz</a></li>
      <li class="nav-item "><a class="nav-link" href="#">About Us</a></li>
      {% if request.user.is_authenticated %}
        <li class="">{{user.username}}</li>
        <li class="nav-item "> <a class="nav-link" href="{% url 'quizapp:logout' %}">Logout</a></li>
      {% else %}
        <li class="nav-item "> <a class="nav-link" href="{% url 'quizapp:login' %}">Login</a></li>
      {% endif %}
    </ul>
  </nav>
<section  style="padding: 80px;">
    {% block content %}
    {% endblock %}
</section>
	<!-- Site footer -->
	<footer style="padding: 25px 0;	text-align: center;	border-top: 1px solid gray;">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <span class="copyright">Copyright&nbsp;© Squeeze 2021</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-linkedin"></i></a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            <li class="list-inline-item"><a href="#">Terms of Use</a></li>
          </ul>
        </div>
      </div>
    </div>
	</footer>

</body>
</html>

quizmakers/templates/create_question.html
{% extends 'base.html' %}
{% block content %}

<section style=" text-align:'center' ">
	<div class="container jumbotron">
		<h3>Now, add questions to the quiz <strong></strong></h3>
		<form action="" method="POST" class="post-form">
			{% csrf_token %}
			
			<div class="input-group mb-5    ">
				<div class="input-group-prepend">
					<span class="input-group-text">Question</span>
				</div>
				{{form.question}}
			</div>
			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Option 1</span>
				</div>
				{{form.opt1}}
			</div>
			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Option 2</span>
				</div>
				{{form.opt2}}
			</div>
			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Option 3</span>
				</div>
				{{form.opt3}}
			</div>
			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Option 4</span>
				</div>
				{{form.opt4}}
			</div>
            <div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Correct</span>
				</div>
				{{form.correct}}
			</div>
			
			
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
</section>

{% endblock %}

quizmakers/templates/create_quiz.html
{% extends 'base.html' %}
{% block content %}

<section style=" text-align:'center' ">
	<div class="container">
		<div class="notification ">
		<h3>Here you can create a quiz!</h3>
		<form action="" method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label for="quiz_name">Name of the Quiz</label>
				<input type="text" class="form-control" name="quiz_name">
			</div>
			<div class="form-group">
				<label for="code">set code for quiz</label>
				<input type="text" placeholder="max 10 characters" class="form-control" name="code">
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>

		{%if cool%}
		<h1 style="color: red;">Code already exists! enter Another</h1>
		{%endif%}
	</div>
	</div>
</section>

{% endblock %}

quizmakers/templates/give_quiz.html
{% extends 'base.html' %}

 {% block content %}

 <div class="container is-widescreen">
	<div class="notification ">
		<form action="" method="POST">
			{% csrf_token %}
		<div class="field">
			<label for ="code" class="label is-large"><h3>Have a Code</h3></label>
			<div class="control has-icons-left has-icons-right">
			  <input id="Inp" class="input is-large" name="code" placeholder="Write code">
			 
			</div>

		</div>
		<button  type="submit" class="button is-success">Go!</button>

		</form>
	 {%if value%}
     <h1 style="color: red;">INVALID CODE</h1>
	 {%endif%}
	</div>
  </div>
  
  <br/><br/>

  <section class="section">
	<h1 class="title">Try sample quiz</h1>
	<h2 class="subtitle">
	  A sample quiz for you all without any need of quiz code and without creating, any of the quiz .<br/>
	  use code <strong>SampleQuiz</strong> for the sample quiz!

	</h2>
    
  </section>
 
  

  
  
	{% endblock %}

quizmakers/templates/landing.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}

{% load static %}
<div style="background-image: url('../static/Images/land.jpeg'); margin: -80px;">    <section >
    <div class="single-slide-item slide-1 landing-page">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="single-slide-item-content">
                        <h2>Quizzy <br> Some Good line</h2>
                         <h3>Tell us what you want to do!!!</h3>
                        <a href="give_quiz"><button type="button" class="slide-btn" >
                       Give quiz
                        </button></a>
                       
                        <a href="create_quiz" ><button type="button"  class="slide-btn">
                            create one 
                            </button></a>
                        </a>
                        
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>
  </div>

{% endblock %}

quizmakers/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #95b9db !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #d6bdec;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						{% if request.GET.next %}
							<input type="hidden" name="next" value="{{ request.GET.next }}">
						{% else %}
							<input type="hidden" name="next" value="">
						{% endif %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'quizapp:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

quizmakers/templates/navin.html
{% extends 'landing.html'%}

{%block content%}
<nav>
    <input type="checkbox" id="check">
    <label for="check" class="checkbtn">
      <i class="fa fa-bars"></i>
    </label>
    <label class="logo">Squeeze</label>
    <ul>
      <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:landing' %}">Home</a></li>
      <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:quiz' %}">Give quiz</a></li>
      <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:create' %}">Create quiz</a></li>
      <li class="nav-item "><a class="nav-link" href="#">About Us</a></li>
      <li class="nav-item "> <a class="nav-link" href="{% url 'quizapp:login' %}">login</a></li>
    </ul>
  </nav> 
{% endblock %}

quizmakers/templates/navout.html
{% extends 'landing.html'%}

{%block content%}
<nav>
  <input type="checkbox" id="check">
  <label for="check" class="checkbtn">
    <i class="fa fa-bars"></i>
  </label>
  <label class="logo">Squeeze</label>
  <ul>
    <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:landing' %}">Home</a></li>
    <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:quiz' %}">Give quiz</a></li>
    <li class="nav-item "><a class="nav-link" href="{% url 'quizapp:create' %}">Create quiz</a></li>
    <li class="nav-item "><a class="nav-link" href="#">About Us</a></li>
    <li class="nav-item "> <a class="nav-link" href="{% url 'quizapp:logout' %}">logout</a></li>
  </ul>
</nav> 
{% endblock %}

quizmakers/templates/quiz_detail.html
{% extends 'base.html' %}
{%block content %}

<div class="container">
	
	<h1 class="border border-secondary rounded-pill text-center">{{quiz.name}}</h1>
	<form action="" method="post">
		{% csrf_token %}
		<div class="quiz_body" style="min-height: 300px;">
		
			{% for que in quiz.questions.all %}
			
			<div class="card" style="margin: 20px 0;">
				<h5 class="card-header"><strong>Que .</strong> {{ que.question }}?</h5>
				<div class="card-body ">
					<div class="custom-control custom-radio">
						<input type="radio" name="{{ que }}" id="{{ que }}.1" value="1" class="custom-control-input">
						<label class="custom-control-label" for="{{ que }}.1">{{que.opt1}}</label>
					</div>
					<div class="custom-control custom-radio">
						<input type="radio" name="{{ que }}" id="{{ que }}.2" value="2" class="custom-control-input">
						<label class="custom-control-label" for="{{ que }}.2">{{que.opt2}}</label>
					</div>
					<div class="custom-control custom-radio">
						<input type="radio" name="{{ que }}" id="{{ que }}.3" value="3" class="custom-control-input">
						<label class="custom-control-label" for="{{ que }}.3">{{que.opt3}}</label>
					</div>
					<div class="custom-control custom-radio">
						<input type="radio" name="{{ que }}" id="{{ que }}.4" value="4" class="custom-control-input">
						<label class="custom-control-label" for="{{ que }}.4">{{que.opt4}}</label>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		<button type="submit" class="btn btn-primary btn-lg btn-block ">Submit</button>
	</form>
</div>

{% endblock %}

quizmakers/templates/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #95b9db !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #d6bdec;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'quizapp:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

quizmakers/templates/result.html
{% extends 'base.html' %}

{% block content %}
<section style=" text-align:'center'">
	<div class="container jumbotron">
			<div class="container is-max-desktop">
				<div class="notification">
					<h3>Here is the result for the quiz :<strong>{{ quiz.name }}</strong></h3>
					<h4>No. of correct responses is : <strong>{{correct}}</strong></h4>

				</div>
			  </div>
</section>
{% endblock %}

quizmakers/templates/sample_quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

quizmakers/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
    <div class="container">
        <div class="row justify-content-around">
            <div class="col-4">
                <a href="{% url 'quizapp:add_question' pk=PK %}">
                    <button type="button" class="btn btn-primary btn-lg btn-block">Add more questions</button>
                </a>
            </div>
            <div class="col-4">
                <a href="{% url 'quizapp:landing' %}">
                    <button  type="button" class="btn btn-primary btn-lg btn-block">Thanks, I'm done!</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}